
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      mongodb:
        condition: service_healthy
  
  gh-service:
    build: ./GithubService/.
    container_name: gh-service
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017
      - SERVICE_PORT=${GITHUB_SERVICE_PORT}
      - TOKEN=${TOKEN:-0}
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl", "http://localhost:8090/health"]
      interval: 20s
      timeout: 20s
      retries: 3
      start_period: 15s

  processing-service:
    build: ./ProcessingService/.
    container_name: proc-service
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017
      - GH_SERVICE_URI=http://gh-service:${GITHUB_SERVICE_PORT}
      - SERVICE_PORT=${PROCESSING_SERVICE_PORT}
    depends_on:
      gh-service:
        condition: service_healthy

  aggregation-1-service:
    build: ./AggregatorService/.
    container_name: aggreagation1-service
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017
      - SERVICE_PORT=${AGGREGATOR_1_SERVICE_PORT}
    depends_on:
      mongodb:
        condition: service_healthy
  
  aggregation-2-service:
    build: ./AggregatorService/.
    container_name: aggreagation2-service
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017
      - SERVICE_PORT=${AGGREGATOR_2_SERVICE_PORT}
    depends_on:
      mongodb:
        condition: service_healthy


  nginx:
    image: nginx:alpine
    ports:
      - $OUT_PORT:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - aggregation-1-service
      - aggregation-2-service
    restart: unless-stopped

volumes:
  mongodb_data:

